### ISSUE TITLE
Conception d'un logo

### ISSUE THREAD

**Issue by lisamaison** [Transrian/projet-TA70#11]

**Comment by lisamaison** [comment]
lié à https://github.com/Transrian/projet-TA70/issues/1

**Comment by jacmartinelli** [comment]
![logo](https://user-images.githubusercontent.com/26342778/41354580-a490e2ce-6f1f-11e8-890e-3d2e44a803bd.png)

**Comment by jacmartinelli** [comment]
![kikela](https://user-images.githubusercontent.com/26342778/42038827-29a2e908-7aec-11e8-8e5f-69c95e08e797.png)
