### ISSUE TITLE
Choisir la technologie

### ISSUE THREAD

**Issue by Transrian** [Transrian/projet-TA70#3]
L’équipe doit définir les technologies et l’environnement de développement adaptés de façon correspondre au mieux aux besoins de l’application

**Comment by lisamaison** [comment]
To do list choix techno : 
- [ ] Choix de la base de données
- [ ] Choix du serveur web
- [ ] Choix du langage front end
- [ ] Choix du langage back end

**Comment by Transrian** [comment]
Techos fixés

**Comment by Transrian** [comment]
Done
